### ISSUE TITLE
v-on:change event not firing.

### ISSUE THREAD

**Issue by TAUFEEQ1** [soundar24/vue-round-slider#2]
Hello Thank you for this tool.
change event is not firing.

**Comment by soundar24** [comment]
Hi @TAUFEEQ1, since this acts like a wrapper for roundSlider the events will be treated as props. So the events should be passed like `v-bind:change="handler"` or `:change="handler"` instead of `v-on`. I have updated the same info in the readme also.

Check the below **demo** and let me know your comments.

#### https://codesandbox.io/s/vue-round-slider-event-binding-x2emq?file=/src/components/SliderDemo.vue

Thanks..

**Comment by TAUFEEQ1** [comment]
Hello, @soundar24 , The change handler is still not firing.

https://codesandbox.io/s/vue-round-slider-event-binding-o0e7j?file=/src/components/SliderDemo.vue

**Comment by soundar24** [comment]
@TAUFEEQ1 yes I can find this issue. While click on the slider range, at that time change event was triggered. But when drag the handle and release, at that time change doesn't triggered (seems broken in the recent release).

I will fix this and release in.a couple of days. Good finding, thanks..

**Comment by soundar24** [comment]
@TAUFEEQ1 The change event related issue was resolved, and updated in the below release [v1.0.1]
#### https://github.com/soundar24/vue-round-slider/releases/tag/v1.0.1

You can simply update to this version and confirm. I have updated in the same demo where change event is working fine.
#### https://codesandbox.io/s/vue-round-slider-event-binding-x2emq

Please check and let me know if you have any other concerns.. thanks...

**Comment by TAUFEEQ1** [comment]
Yes its working, Thank you.
