### ISSUE TITLE
[Feature] Add flat slider

### ISSUE THREAD

**Issue by BennyAlex** [soundar24/vue-round-slider#7]
Hey @soundar24 ,

it's me again :)

another cool thing would be a flat slider.

Currently I am using two sliders on my page, the flat slider is showing on desktop and a round slider is used on mobile, because the space is limited.

If I could just use your slider also as a flat one that would be nice.

**Comment by soundar24** [comment]
@BennyAlex Actually the round slider logic is totally different from the flat slider, so we can't integrate that behaviour here. Maybe for your case I can suggest to use another flat slider plugin based on the conditional basis. If the environment is mobile then you can initialize round slider otherwise you can initialze the flat slider.

**Comment by soundar24** [comment]
This is the out of scope, so closing this. If any concerns then you can re-open and update your comments.

**Comment by BennyAlex** [comment]
Its just really annoying that there is no slider wich provides both functionalities and the website gets much larger with 2 sliders and you have to maintain both.
Btw, do you plan to release a vue only version, without jquery? Its really bad to include another 'framework' inside anothers, and jquery is really large and slow.

**Comment by soundar24** [comment]
yes, mostly none of the sliders doesn't having both the functionalities. since even both are the number sliders, their functionality was totally different.

And I already had the plan to remove the jQuery dependency from a long back, but that's a complete revamp and I don't have the enough time for that. Hopefully I will try to have a look on that again, but not nearby..
